Repository projectceladon/linux-intel-lts2023, pull requests merged in 2025-05, with the labels that each got.

#46 x86/mtrr: Check if fixed-range MTRR exists in mtrr_save_fixed_ranges()
  arch/x86/kernel/cpu/mtrr/generic.c
Labels: Developer Approved, PR approved, Valid commit message, Engineering Build Successful

#45 drm/virtio: process virtgpu bo before bo free
  drivers/gpu/drm/virtio/virtgpu_object.c
Labels: Developer Approved, PR approved, Valid commit message, Engineering Build Successful

#48 drm/virtio: pass correct plane index to backend
  drivers/gpu/drm/virtio/virtgpu_display.c
  drivers/gpu/drm/virtio/virtgpu_drv.h
  drivers/gpu/drm/virtio/virtgpu_plane.c
Labels: Developer Approved, PR approved, Valid commit message, Engineering Build Failed

#47 drm/virtio: wait all work done before reset device
  drivers/gpu/drm/virtio/virtgpu_drv.c
Labels: Developer Approved, PR approved, Valid commit message, Engineering Build Successful

#51 drm/virtio: avoid virtio gpu resume deadlock
  drivers/gpu/drm/virtio/virtgpu_drv.c
  drivers/gpu/drm/virtio/virtgpu_drv.h
  drivers/gpu/drm/virtio/virtgpu_kms.c
  drivers/gpu/drm/virtio/virtgpu_vq.c
Labels: Developer Approved, PR approved, Valid commit message, Engineering Build Successful

#59 drm/virtio: Use drm_err instead of WARN upon vblank timeout
  drivers/gpu/drm/virtio/virtgpu_display.c
Labels: Developer Approved, PR approved, Engineering Build Successful
